# New Setup
version: '3'

services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'spring-blog-postgres'
    environment:
      - POSTGRES_DB=spring-blog
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
